---
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
---
helm repo update
---
helm install prometheus prometheus-community/kube-prometheus-stack \
  --namespace monitoring \
  --create-namespace \
  --set alertmanager.persistentVolume.storageClass="gp2",server.persistentVolume.storageClass="gp2"
---
kubectl port-forward svc/prometheus-kube-prometheus-prometheus -n monitoring 4001:9090
----
kubectl get secret -n monitoring prometheus-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo